source $VIMRUNTIME/defaults.vim

set nocompatible
set ff=unix
set nobackup
set noundofile
set ts=4
set sts=4
set sw=4
set et
set hlsearch
set incsearch
set ignorecase
set lines=50 columns=200

set shell=powershell.exe\ -ExecutionPolicy\ Bypass
